steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/terrific-terraform/fib-cloud-run:latest', 
         '--cache-from', 'gcr.io/terrific-terraform/fib-cloud-run:latest', './fib-cloud-run']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/terrific-terraform/fib-cloud-run']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'terrific-terraform', '--image', 'gcr.io/terrific-terraform/fib-cloud-run', '--region', 'us-central1','--platform', 'managed']
images:
- gcr.io/terrific-terraform/fib-cloud-run:latest